# 应用名称
spring:
  application:
    name: item
  # MySql数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myitem?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1234

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 占用端口
server:
  port: 8080

logging:
  level:
    # root：全局所有包默认级别
    root: INFO
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: item-java
    region: cn-beijing
    domain: https://item-java.oss-cn-beijing.aliyuncs.com
