# 应用名称
spring:
  application:
    name: item
  # MySql数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myitem?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: HWjruzI0G/pp5PQpX0fnf3WpXZIi5hZmmEpNM5ePNyElBp/0ls+LJ7vlazhAMD00gucV/inrC2UnK4GGQn+MvQ==
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      # 启用 Filter
      filter:
        config:
          enabled: true
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
      stat-view-servlet:
        enabled: true          # 开启监控页面
        url-pattern: /druid/*  # 访问路径
        login-username: admin  # 登录账号
        login-password: admin  # 登录密码
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIHYXsX6nwsEQKA1mFqP74riDvy80y0mNlcxscAu7tV77EIffKegJstoul48DZOn1+j8W2jdY9nBBd93rxqh5MsCAwEAAQ==
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 占用端口
server:
  port: 8081
  # tomcat线程池配置
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100
    connection-timeout: 20000

logging:
  level:
    # root：全局所有包默认级别
    root: INFO

file:
  upload:
    root-path: ./data

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: item-java
    region: cn-beijing
    domain: https://item-java.oss-cn-beijing.aliyuncs.com